export const GET_FILTERS = 'GET_FILTERS';
export const GET_FILTERS_PENDING = 'GET_FILTERS_PENDING';
export const GET_FILTERS_FULFILLED = 'GET_FILTERS_FULFILLED';
export const GET_FILTERS_REJECTED = 'GET_FILTERS_REJECTED';

export const ADD_DRINKS = 'ADD_DRINKS';
export const ADD_DRINKS_PENDING = 'ADD_DRINKS_PENDING';
export const ADD_DRINKS_FULFILLED = 'ADD_DRINKS_FULFILLED';
export const ADD_DRINKS_REJECTED = 'ADD_DRINKS_REJECTED';
