export const GET_FILTERS = 'GET_FILTERS';
export const GET_FILTERS_PENDING = 'GET_FILTERS_PENDING';
export const GET_FILTERS_FULFILLED = 'GET_FILTERS_FULFILLED';
export const GET_FILTERS_REJECTED = 'GET_FILTERS_REJECTED';

export const GET_DRINKS = 'GET_DRINKS';
export const GET_DRINKS_PENDING = 'GET_DRINKS_PENDING';
export const GET_DRINKS_FULFILLED = 'GET_DRINKS_FULFILLED';
export const GET_DRINKS_REJECTED = 'GET_DRINKS_REJECTED';
